version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - edgarrmondragon
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    reviewers:
      - edgarrmondragon
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - edgarrmondragon
