# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile
config:
  send_anonymous_usage_stats: false
  use_colors: true

dbt_sqlite:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: database
      schema: main
      schemas_and_paths:
        main: "{{ env_var('PWD') }}/dbs/etl.db"
        retail: "{{ env_var('PWD') }}/dbs/retail.db"
      schema_directory: "{{ env_var('PWD') }}/dbs"
