[tool.poetry]
name = "dbt-sqlite-test"
version = "0.1.0"
description = "Testing dbt with SQLite"
authors = ["Edgar Ramírez Mondragón <edgarrm358@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
kaggle = "^1.5.12"
dbt-core = "^0.20.2"
dbt-sqlite = "^0.2.1"

[tool.poetry.dev-dependencies]
sqlfluff = {extras = ["dbt"], version = "^0.6.9"}

[tool.sqlfluff.core]
templater = "dbt"
exclude_rules = "L005"

[tool.sqlfluff.rules]
tab_space_size = 2
comma_style = "leading"
max_line_length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
