name: Lint dbt models

on: push

jobs:
  lint_dbt:
    name: Lint SQL models using SQLFluff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Dependencies
        env:
          PIP_CONSTRAINT: .github/workflows/constraints.txt
        run: |
          pipx install poetry
          poetry install

      - name: Lint models
        env:
          DBT_PROFILES_DIR: "./"
        run: make lint
