name: Test

on: push

env:
  PIP_CONSTRAINT: .github/workflows/constraints.txt

jobs:
  test:
    name: Test data using dbt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: x64

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version

      - name: Install project dependencies
        run: |
          poetry env use python3.11
          poetry install

      - name: Test models
        env:
          DBT_PROFILES_DIR: "./"
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: make test

  lint_dbt:
    name: Lint SQL models using SQLFluff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: x64

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version

      - name: Install project dependencies
        run: |
          poetry env use python3.11
          poetry install

      - name: Lint models
        env:
          DBT_PROFILES_DIR: "./"
        run: make lint
